
#ifndef _BASE_TYPE_H_
#define _BASE_TYPE_H_


#ifndef _MSC_VER //Not for Visual compiler
#include <inttypes.h>
#endif

#include <stdio.h>
#include <stddef.h>
#include <assert.h>

#if !defined(__APPLE__)
#include <cstddef>
#endif


enum XCHG_TYPE_ENUM
{
	XCHG_TYPE_CATIA_V5=-4,
	XCHG_TYPE_CATIA=-3,
	XCHG_TYPE_SKIP=-2,
	XCHG_TYPE_ERROR=-1,
	XCHG_TYPE_UNKNOWN=0,
	XCHG_TYPE_DIRECTION=1,
	XCHG_TYPE_VECTOR=2,
	XCHG_TYPE_PLACEMENT=10,
	XCHG_TYPE_AXIS1_PLACEMENT=11,
	XCHG_TYPE_AXIS2_PLACEMENT_2D=12,
	XCHG_TYPE_AXIS2_PLACEMENT_3D=13,
	XCHG_TYPE_AXIS2_PLACEMENT=14,
	XCHG_TYPE_AXIS_SYSTEM = 15,
	XCHG_TYPE_CARTESIAN_TRANSFORMATION_OPERATOR=20,
	XCHG_TYPE_CARTESIAN_TRANSFORMATION_OPERATOR_2D=21,
	XCHG_TYPE_CARTESIAN_TRANSFORMATION_OPERATOR_3D=22,
	XCHG_TYPE_CARTESIAN_POINT=30,
	XCHG_TYPE_POINT_ON_CURVE=31,
	XCHG_TYPE_POINT_ON_SURFACE=32,
	XCHG_TYPE_DEGENERATE_PCURVE=33,
	XCHG_TYPE_EVALUATED_DEGENERATE_PCURVE=34,
	XCHG_TYPE_POINT_REPLICA=35,
	XCHG_TYPE_PNT=36,
	XCHG_TYPE_CARTESIAN_POINT_WITH_INFOS=37,
	XCHG_TYPE_LINE=100,
	XCHG_TYPE_POLYLINE=101,
	XCHG_TYPE_CONIC=110,
	XCHG_TYPE_CIRCLE=111,
	XCHG_TYPE_ELLIPSE=112,
	XCHG_TYPE_HYPERBOLA=113,
	XCHG_TYPE_PARABOLA=114,
	XCHG_TYPE_SPIRAL=115,
	XCHG_TYPE_HELIX=116,
	XCHG_TYPE_SUPER_CURVE=119,
	XCHG_TYPE_CURVE=120,
	XCHG_TYPE_UNIFORM_CURVE=121,
	XCHG_TYPE_QUASI_UNIFORM_CURVE=122,
	XCHG_TYPE_BEZIER_CURVE=123,
	XCHG_TYPE_B_SPLINE_CURVE_WITH_KNOTS=124,
	XCHG_TYPE_RATIONAL_B_SPLINE_CURVE=125,
	XCHG_TYPE_RATIONAL_B_SPLINE_CURVE_WITH_KNOTS=126,
	XCHG_TYPE_B_SPLINE_CURVE=127,
	XCHG_TYPE_TRIMMED_CURVE=130,
	XCHG_TYPE_PCURVE=140,
	XCHG_TYPE_CURVE_REPLICA=150,
	XCHG_TYPE_PARAMETRIC_CURVE=151,
	XCHG_TYPE_SINGLE_PARAMETER_CONSTRAINT=152,
	XCHG_TYPE_COMPOSITE_CURVE=160,
	XCHG_TYPE_COMPOSITE_CURVE_ON_SURFACE=161,
	XCHG_TYPE_BOUNDARY_CURVE=162,
	XCHG_TYPE_OUTER_BOUNDARY_CURVE=163,
	XCHG_TYPE_COMPOSITE_CURVE_SEGMENT=170,
	XCHG_TYPE_REPARAMETRISED_COMPOSITE_CURVE_SEGMENT=171,
	XCHG_TYPE_OFFSET_CURVE_2D=180,
	XCHG_TYPE_OFFSET_CURVE_3D=181,
	XCHG_TYPE_SURFACE_CURVE=190,
	XCHG_TYPE_INTERSECTION_CURVE=191,
	XCHG_TYPE_SEAM_CURVE=192,
	XCHG_TYPE_ELEMENTARY_SURFACE=200,
	XCHG_TYPE_PLANE=201,
	XCHG_TYPE_CYLINDRICAL_SURFACE=202,
	XCHG_TYPE_CONICAL_SURFACE=203,
	XCHG_TYPE_SPHERICAL_SURFACE=204,
	XCHG_TYPE_TOROIDAL_SURFACE=205,
	XCHG_TYPE_SWEPT_SURFACE=210,
	XCHG_TYPE_SURFACE_OF_LINEAR_EXTRUSION=211,
	XCHG_TYPE_SURFACE_OF_REVOLUTION=212,
	XCHG_TYPE_RULED_SURFACE=213,
	XCHG_TYPE_BLEND_SURFACE=214,
	XCHG_TYPE_NET=215,
	XCHG_TYPE_RECTANGULAR_COMPOSITE_SURFACE=220,
	XCHG_TYPE_RECTANGULAR_TRIMMED_SURFACE=221,
	XCHG_TYPE_CURVE_BOUNDED_SURFACE=222,
	XCHG_TYPE_SURFACE_PATCH=223,
	XCHG_TYPE_B_SPLINE_SURFACE=230,
	XCHG_TYPE_B_SPLINE_SURFACE_WITH_KNOTS=231,
	XCHG_TYPE_UNIFORM_SURFACE=232,
	XCHG_TYPE_QUASI_UNIFORM_SURFACE=233,
	XCHG_TYPE_BEZIER_SURFACE=234,
	XCHG_TYPE_RATIONAL_B_SPLINE_SURFACE=235,
	XCHG_TYPE_RATIONAL_B_SPLINE_SURFACE_WITH_KNOTS=236,
	XCHG_TYPE_SURFACE=237,
	XCHG_TYPE_OFFSET_SURFACE=240,
	XCHG_TYPE_FILLET_SURFACE=244,
	XCHG_TYPE_PARAMETRIC_SURFACE=245,
	XCHG_TYPE_SURFACE_REPLICA=250,
	XCHG_TYPE_SUPER_SURFACE=251,
	XCHG_TYPE_GEOMETRIC_CURVE_SET=260,
	XCHG_TYPE_GEOMETRIC_SET_REPLICA=261,
	XCHG_TYPE_GEOMETRIC_SET=262,
	XCHG_TYPE_GEOMETRIC_SET_SELECT=263,
	XCHG_TYPE_GEOMETRIC_SET_SELECT_ENTITY=264,
	XCHG_TYPE_VERTEX=300,
	XCHG_TYPE_EDGE_CURVE=310,
	XCHG_TYPE_ORIENTED_EDGE=311,
	XCHG_TYPE_EDGE=312,
	XCHG_TYPE_CONNECTED_EDGE_SET=313,
	XCHG_TYPE_EDGE_BASED_WIREFRAME_MODEL=314,
	XCHG_TYPE_VERTEX_LOOP=320,
	XCHG_TYPE_EDGE_LOOP=321,
	XCHG_TYPE_POLY_LOOP=322,
	XCHG_TYPE_LOOP=323,
	XCHG_TYPE_FACE_BOUND=330,
	XCHG_TYPE_FACE_OUTER_BOUND=331,
	XCHG_TYPE_FACE_SURFACE=332,
	XCHG_TYPE_ORIENTED_FACE=333,
	XCHG_TYPE_ADVANCED_FACE=334,
	XCHG_TYPE_SUBFACE=335,
	XCHG_TYPE_FACE=336,
	XCHG_TYPE_VERTEX_SHELL=340,
	XCHG_TYPE_WIRE_SHELL=341,
	XCHG_TYPE_OPEN_SHELL=342,
	XCHG_TYPE_ORIENTED_OPEN_SHELL=343,
	XCHG_TYPE_CLOSED_SHELL=344,
	XCHG_TYPE_ORIENTED_CLOSED_SHELL=345,
	XCHG_TYPE_CONNECTED_FACE_SET=346,
	XCHG_TYPE_SHELL_BASED_WIREFRAME_REPRESENTATION=347,
	XCHG_TYPE_SHELL_BASED_WIREFRAME_MODEL=348,
	XCHG_TYPE_SHELL_BASED_SURFACE_MODEL=349,
	XCHG_TYPE_FACE_BASED_SURFACE_MODEL=350,
	XCHG_TYPE_SHELL=351,
	XCHG_TYPE_SURFACE_MODEL=352,
	XCHG_TYPE_WIREFRAME_MODEL=353,
	XCHG_TYPE_ORIENTED_PATH=360,
	XCHG_TYPE_OPEN_PATH=361,
	XCHG_TYPE_PATH=362,
	XCHG_TYPE_EDGE_ENTITY=365,
	XCHG_TYPE_FACE_ENTITY=366,
	XCHG_TYPE_PATH_ENTITY=367,
	XCHG_TYPE_CONNECTED_FACE_SET_ENTITY=368,
	XCHG_TYPE_LIST_OF_REVERSIBLE_TOPOLOGY_ITEM=370,
	XCHG_TYPE_SET_OF_REVERSIBLE_TOPOLOGY_ITEM=371,
	XCHG_TYPE_REVERSIBLE_TOPOLOGY_ITEM=372,
	XCHG_TYPE_REVERSIBLE_TOPOLOGY=373,
	XCHG_TYPE_TOPOLOGICAL_REPRESENTATION_ITEM=374,
	XCHG_TYPE_EDGE_BASED_WIREFRAME_REPRESENTATION=380,
	XCHG_TYPE_GEOMETRICALLY_BOUNDED_SURFACE_REPRESENTATION=381,
	XCHG_TYPE_GEOMETRICALLY_BOUNDED_WIREFRAME_REPRESENTATION=382,
	XCHG_TYPE_FACETTED_BREP_REPRESENTATION=383,
	XCHG_TYPE_MANIFOLD_SURFACE_WITH_TOPOLOGY_REPRESENTATION=384,
	XCHG_TYPE_ADVANCED_BREP_REPRESENTATION=385,
	XCHG_TYPE_BREP_WITH_VOIDS=390,
	XCHG_TYPE_FACETTED_BREP=391,
	XCHG_TYPE_MANIFOLD_SOLID_BREP=392,
	XCHG_TYPE_SOLID_REPLICA=393,
	XCHG_TYPE_SOLID_MODEL=394,
	XCHG_TYPE_PIPING_ENTITY=395,
	XCHG_TYPE_CALENDAR_DATE=500,
	XCHG_TYPE_ORDINAL_DATE=501,
	XCHG_TYPE_WEEK_OF_YEAR_AND_DAY_DATE=502,
	XCHG_TYPE_DATE_STEP=503,
	XCHG_TYPE_DATE_TIME_ROLE=504,
	XCHG_TYPE_COORDINATED_UNIVERSAL_TIME_OFFSET=505,
	XCHG_TYPE_LOCAL_TIME=506,
	XCHG_TYPE_DATE_AND_TIME=507,
	XCHG_TYPE_DATE_TIME_SELECT=508,
	XCHG_TYPE_APPROVAL_DATE_TIME=509,
	XCHG_TYPE_DATED_EFFECTIVITY=510,
	XCHG_TYPE_DATE_TIME_ITEM=511,
	XCHG_TYPE_CC_DESIGN_DATE_AND_TIME_ASSIGNMENT=512,
	XCHG_TYPE_DATE_AND_TIME_ASSIGNMENT=513,
	XCHG_TYPE_LENGTH_MEASURE_WITH_UNIT=520,
	XCHG_TYPE_MASS_MEASURE_WITH_UNIT=521,
	XCHG_TYPE_PLANE_ANGLE_MEASURE_WITH_UNIT=522,
	XCHG_TYPE_SOLID_ANGLE_MEASURE_WITH_UNIT=523,
	XCHG_TYPE_AREA_MEASURE_WITH_UNIT=524,
	XCHG_TYPE_VOLUME_MEASURE_WITH_UNIT=525,
	XCHG_TYPE_MEASURE_WITH_UNIT=526,
	XCHG_TYPE_LENGTH_MEASURE=530,
	XCHG_TYPE_MASS_MEASURE=531,
	XCHG_TYPE_PLANE_ANGLE_MEASURE=532,
	XCHG_TYPE_SOLID_ANGLE_MEASURE=533,
	XCHG_TYPE_AREA_MEASURE=534,
	XCHG_TYPE_VOLUME_MEASURE=535,
	XCHG_TYPE_COUNT_MEASURE=536,
	XCHG_TYPE_CONTEXT_DEPENDENT_MEASURE=537,
	XCHG_TYPE_DESCRIPTIVE_MEASURE=538,
	XCHG_TYPE_POSITIVE_LENGTH_MEASURE=539,
	XCHG_TYPE_POSITIVE_PLANE_ANGLE_MEASURE=540,
	XCHG_TYPE_CONVERSION_BASED_UNIT=541,
	XCHG_TYPE_CONTEXT_DEPENDENT_UNIT=542,
	XCHG_TYPE_SI_UNIT=543,
	XCHG_TYPE_UNCERTAINTY_MEASURE_WITH_UNIT=544,
	XCHG_TYPE_LENGTH_UNIT=545,
	XCHG_TYPE_MASS_UNIT=546,
	XCHG_TYPE_AREA_UNIT=550,
	XCHG_TYPE_PLANE_ANGLE_UNIT=553,
	XCHG_TYPE_SOLID_ANGLE_UNIT=554,
	XCHG_TYPE_VOLUME_UNIT=555,
	XCHG_TYPE_APPLICATION_CONTEXT=600,
	XCHG_TYPE_APPLICATION_CONTEXT_ELEMENT=601,
	XCHG_TYPE_CONFIGURATION_ITEM=602,
	XCHG_TYPE_CONFIGURATION_DESIGN=603,
	XCHG_TYPE_PRODUCT_DEFINITION_WITH_ASSOCIATED_DOCUMENTS=610,
	XCHG_TYPE_PRODUCT_CONCEPT_CONTEXT=611,
	XCHG_TYPE_PRODUCT_CONTEXT=612,
	XCHG_TYPE_PRODUCT_DEFINITION_CONTEXT=613,
	XCHG_TYPE_PRODUCT=614,
	XCHG_TYPE_PRODUCT_VERSION=615,
	XCHG_TYPE_WORK_ITEM=616,
	XCHG_TYPE_CHANGE_REQUEST_ITEM=617,
	XCHG_TYPE_START_REQUEST_ITEM=618,
	XCHG_TYPE_CONTRACTED_ITEM=619,
	XCHG_TYPE_CONTEXT_DEPENDENT_SHAPE_REPRESENTATION=620,
	XCHG_TYPE_PRODUCT_DEFINITION=621,
	XCHG_TYPE_MECHANICAL_CONTEXT=622,
	XCHG_TYPE_NEXT_ASSEMBLY_USAGE_OCCURENCE=630,
	XCHG_TYPE_PROMISSORY_USAGE_OCCURENCE=631,
	XCHG_TYPE_ASSEMBLY_COMPONENT_USAGE=632,
	XCHG_TYPE_PRODUCT_DEFINITION_USAGE=633,
	XCHG_TYPE_QUANTIFIED_ASSEMBLY_COMPONENT_USAGE=634,
	XCHG_TYPE_ASSEMBLY_COMPONENT_USAGE_SUBSTITUTE=635,
	XCHG_TYPE_SPECIFIED_HIGHER_USAGE_OCCURRENCE=636,
	XCHG_TYPE_SERIAL_NUMBERED_EFFECTIVITY=640,
	XCHG_TYPE_LOT_EFFECTIVITY=641,
	XCHG_TYPE_PLANNED_EFFECTIVITY=642,
	XCHG_TYPE_EFFECTIVITY=643,
	XCHG_TYPE_CONFIGURATION_EFFECTIVITY=644,
	XCHG_TYPE_REQUESTED_ACTION=650,
	XCHG_TYPE_ORDERED_ACTION=651,
	XCHG_TYPE_ACTION_METHOD=652,
	XCHG_TYPE_ACTION=653,
	XCHG_TYPE_ACTION_EXECUTION=654,
	XCHG_TYPE_ACTION_STATUS=655,
	XCHG_TYPE_ACTION_REQUEST_STATUS=656,
	XCHG_TYPE_EXECUTED_ACTION=657,
	XCHG_TYPE_DIRECTED_ACTION=658,
	XCHG_TYPE_CHANGE=660,
	XCHG_TYPE_CHANGE_REQUEST=661,
	XCHG_TYPE_SECURITY_CLASSIFICATION_LEVEL=662,
	XCHG_TYPE_SECURITY_CLASSIFICATION=663,
	XCHG_TYPE_START_REQUEST=670,
	XCHG_TYPE_START_WORK=671,
	XCHG_TYPE_CERTIFICATION=672,
	XCHG_TYPE_CONTRACT=673,
	XCHG_TYPE_APPROVED_ITEM=680,
	XCHG_TYPE_CLASSIFIED_ITEM=681,
	XCHG_TYPE_PERSON_ORGANIZATION_ITEM=682,
	XCHG_TYPE_SPECIFIED_ITEM=683,
	XCHG_TYPE_PRODUCT_DEFINITION_RELATIONSHIP=690,
	XCHG_TYPE_CHARACTERIZED_PRODUCT_DEFINITION=691,
	XCHG_TYPE_PRODUCT_DEFINITION_SHAPE=692,
	XCHG_TYPE_PRODUCT_DEFINITION_FORMATION=693,
	XCHG_TYPE_PRODUCT_DEFINITION_FORMATION_WITH_SPECIFIED_SOURCE=694,
	XCHG_TYPE_DESIGN_CONTEXT=695,
	XCHG_TYPE_REPRESENTATION_CONTEXT=700,
	XCHG_TYPE_REPRESENTATION_ITEM=701,
	XCHG_TYPE_PARAMETRIC_REPRESENTATION_CONTEXT=702,
	XCHG_TYPE_DEFINITIONAL_REPRESENTATION_ITEM=703,
	XCHG_TYPE_REPRESENTATION=704,
	XCHG_TYPE_DEFINITIONAL_REPRESENTATION=705,
	XCHG_TYPE_SHAPE_REPRESENTATION_RELATIONSHIP=706,
	XCHG_TYPE_REPRESENTATION_RELATIONSHIP_WITH_TRANSFORMATION=707,
	XCHG_TYPE_REPRESENTATION_MAP=708,
	XCHG_TYPE_GEOMETRIC_REPRESENTATION_CONTEXT=709,
	XCHG_TYPE_GEOMETRIC_REPRESENTATION_ITEM=710,
	XCHG_TYPE_MAPPED_ITEM=711,
	XCHG_TYPE_REPRESENTATION_RELATIONSHIP=712,
	XCHG_TYPE_SHAPE_REPRESENTATION=720,
	XCHG_TYPE_SHELL_BASED_WIREFRAME_SHAPE_REPRESENTATION=725,
	XCHG_TYPE_ADVANCED_BREP_SHAPE_REPRESENTATION=726,
	XCHG_TYPE_MANIFOLD_SURFACE_SHAPE_REPRESENTATION=727,
	XCHG_TYPE_GEOMETRICALLY_BOUNDED_SURFACE_SHAPE_REPRESENTATION=728,
	XCHG_TYPE_GEOMETRICALLY_BOUNDED_WIREFRAME_SHAPE_REPRESENTATION=729,
	XCHG_TYPE_SHAPE_ASPECT_RELATIONSHIP=721,
	XCHG_TYPE_SHAPE_DEFINITION=722,
	XCHG_TYPE_SHAPE_DEFINITION_REPRESENTATION=723,
	XCHG_TYPE_SHAPE_ASPECT=724,
	XCHG_TYPE_DESIGN_MAKE_FROM_RELATIONSHIP=730,
	XCHG_TYPE_SUPPLIED_PART_RELATIONSHIP=731,
	XCHG_TYPE_CERTIFIED_ITEM=732,
	XCHG_TYPE_PRODUCT_CATEGORY=733,
	XCHG_TYPE_PRODUCT_RELATED_PRODUCT_CATEGORY=734,
	XCHG_TYPE_PRODUCT_CATEGORY_RELATIONSHIP=735,
	XCHG_TYPE_PRODUCT_VERSION_WITH_SPECIFIED_SOURCE=736,
	XCHG_TYPE_ALTERNATE_PRODUCT_RELATIONSHIP=737,
	XCHG_TYPE_ACTION_REQUEST_ASSIGNMENT=740,
	XCHG_TYPE_ACTION_ASSIGNMENT=741,
	XCHG_TYPE_CERTIFICATION_ASSIGNMENT=742,
	XCHG_TYPE_APPROVAL_ASSIGNMENT=743,
	XCHG_TYPE_CONTRACT_ASSIGNMENT=744,
	XCHG_TYPE_SECURITY_CLASSIFICATION_ASSIGNMENT=745,
	XCHG_TYPE_PERSON=750,
	XCHG_TYPE_ORGANIZATION=751,
	XCHG_TYPE_PERSON_AND_ORGANIZATION_ROLE=752,
	XCHG_TYPE_PERSON_ORGANIZATION_SELECT=753,
	XCHG_TYPE_PERSON_AND_ORGANIZATION=754,
	XCHG_TYPE_PERSON_AND_ORGANIZATION_ASSIGNMENT=755,
	XCHG_TYPE_ORGANIZATION_RELATIONSHIP=756,
	XCHG_TYPE_APPROVAL=760,
	XCHG_TYPE_APPROVAL_STATUS=761,
	XCHG_TYPE_APPROVAL_ROLE=762,
	XCHG_TYPE_APPROVAL_PERSON_ORGANIZATION=763,
	XCHG_TYPE_APPROVAL_RELATIONSHIP=764,
	XCHG_TYPE_PERSONAL_ADDRESS=770,
	XCHG_TYPE_ADDRESS=771,
	XCHG_TYPE_ORGANIZATIONAL_ADDRESS=772,
	XCHG_TYPE_FUNCTIONALLY_DEFINED_TRANSFORMATION=780,
	XCHG_TYPE_ITEM_DEFINED_TRANSFORMATION=781,
	XCHG_TYPE_TRANSFORMATION=782,
	XCHG_TYPE_CC_DESIGN_CERTIFICATION=790,
	XCHG_TYPE_CC_DESIGN_APPROVAL=791,
	XCHG_TYPE_CC_DESIGN_CONTRACT=792,
	XCHG_TYPE_CC_DESIGN_SECURITY_CLASSIFICATION=793,
	XCHG_TYPE_CC_DESIGN_PERSON_AND_ORGANIZATION_ASSIGNMENT=794,
	XCHG_TYPE_CC_DESIGN_SPECIFICATION_REFERENCE=795,
	XCHG_TYPE_PROPERTY_DEFINITION=800,
	XCHG_TYPE_PRE_DEFINED_TERMINATOR_SYMBOL=801,
	XCHG_TYPE_PRE_DEFINED_POINT_MARKER_SYMBOL=802,
	XCHG_TYPE_PRE_DEFINED_DIMENSION_SYMBOL=803,
	XCHG_TYPE_PRE_DEFINED_GEOMETRICAL_TOLERANCE_SYMBOL=804,
	XCHG_TYPE_DRAUGHTING_PRE_DEFINED_COLOUR=805,
	XCHG_TYPE_DRAUGHTING_PRE_DEFINED_CURVE_FONT=806,
	XCHG_TYPE_PRE_DEFINED_CURVE_FONT=807,
	XCHG_TYPE_PRE_DEFINED_SYMBOL=808,
	XCHG_TYPE_PRE_DEFINED_COLOUR=809,
	XCHG_TYPE_PRE_DEFINED_ITEM=810,
	XCHG_TYPE_LEADER_CURVE=811,
	XCHG_TYPE_PROJECTION_CURVE=812,
	XCHG_TYPE_DIMENSION_CURVE=813,
	XCHG_TYPE_ONE_DIRECTION_REPEAT_FACTOR=814,
	XCHG_TYPE_TWO_DIRECTION_REPEAT_FACTOR=815,
	XCHG_TYPE_LEADER_TERMINATOR=816,
	XCHG_TYPE_DIMENSION_CURVE_TERMINATOR=817,
	XCHG_TYPE_TERMINATOR_SYMBOL=818,
	XCHG_TYPE_DEFINED_SYMBOL_SELECT=819,
	XCHG_TYPE_SYMBOL_TARGET=820,
	XCHG_TYPE_DEFINED_SYMBOL=821,
	XCHG_TYPE_COLOUR_RGB=822,
	XCHG_TYPE_COLOUR_SPECIFICATION=823,
	XCHG_TYPE_COLOUR=824,
	XCHG_TYPE_SYMBOL_COLOUR=825,
	XCHG_TYPE_SYMBOL_STYLE_SELECT=826,
	XCHG_TYPE_TEXT_STYLE_FOR_DEFINED_FONT=827,
	XCHG_TYPE_CHARACTER_STYLE_SELECT=828,
	XCHG_TYPE_CURVE_STYLE_FONT=829,
	XCHG_TYPE_CURVE_STYLE_FONT_SELECT=830,
	XCHG_TYPE_CURVE_FONT_OR_SCALED_CURVE_STYLE_FONT_SELECT=831,
	XCHG_TYPE_FILL_AREA_STYLE=832,
	XCHG_TYPE_SYMBOL_STYLE=833,
	XCHG_TYPE_CURVE_STYLE=834,
	XCHG_TYPE_FILL_AREA_STYLE_HATCHING=835,
	XCHG_TYPE_FILL_AREA_STYLE_TILE_SYMBOL_WITH_STYLE=836,
	XCHG_TYPE_FILL_AREA_STYLE_TILE_SHAPE_SELECT=837,
	XCHG_TYPE_FILL_AREA_STYLE_TILES=838,
	XCHG_TYPE_FILL_AREA_STYLE_COLOUR=839,
	XCHG_TYPE_FILL_STYLE_SELECT=840,
	XCHG_TYPE_TEXT_STYLE=841,
	XCHG_TYPE_PRESENTATION_STYLE_SELECT=842,
	XCHG_TYPE_PRESENTATION_STYLE_ASSIGNMENT=843,
	XCHG_TYPE_ANNOTATION_TEXT_OCCURRENCE=844,
	XCHG_TYPE_ANNOTATION_SUBFIGURE_OCCURRENCE=845,
	XCHG_TYPE_ANNOTATION_FILL_AREA_OCCURRENCE=846,
	XCHG_TYPE_ANNOTATION_FILL_AREA=847,
	XCHG_TYPE_ANNOTATION_CURVE_OCCURRENCE=848,
	XCHG_TYPE_ANNOTATION_SYMBOL_OCCURRENCE=849,
	XCHG_TYPE_ANNOTATION_OCCURRENCE=850,
	XCHG_TYPE_DRAUGHTING_CALLOUT_ELEMENT=851,
	XCHG_TYPE_ANGULAR_DIMENSION=852,
	XCHG_TYPE_CURVE_DIMENSION=853,
	XCHG_TYPE_DIAMETER_DIMENSION=854,
	XCHG_TYPE_LINEAR_DIMENSION=855,
	XCHG_TYPE_RADIUS_DIMENSION=856,
	XCHG_TYPE_ORDINATE_DIMENSION=857,
	XCHG_TYPE_PROJECTION_DIRECTED_CALLOUT=858,
	XCHG_TYPE_DIMENSION_CURVE_DIRECTED_CALLOUT=859,
	XCHG_TYPE_DRAUGHTING_CALLOUT=860,
	XCHG_TYPE_DRAUGHTING_PRE_DEFINED_TEXT_FONT=861,
	XCHG_TYPE_PRE_DEFINED_TEXT_FONT=862,
	XCHG_TYPE_FONT_SELECT=863,
	XCHG_TYPE_TEXT_LITERAL=864,
	XCHG_TYPE_TEXT_OR_CHARACTER=865,
	XCHG_TYPE_COMPOSITE_TEXT=866,
	XCHG_TYPE_TEXT_STYLE_WITH_MIRROR=867,
	XCHG_TYPE_TEXT_STYLE_WITH_BOX_CHARACTERISTICS=868,
	XCHG_TYPE_DRAWING_REPLICA=869,
	XCHG_TYPE_SYMBOL=870,
	XCHG_TYPE_SPHERE=871,
	XCHG_TYPE_BLOCK=872,
	XCHG_TYPE_RIGHT_ANGULAR_WEDGE=873,
	XCHG_TYPE_TORUS=874,
	XCHG_TYPE_RIGHT_CIRCULAR_CYLINDER=875,
	XCHG_TYPE_RIGHT_CIRCULAR_CONE=876,
	XCHG_TYPE_HALF_SPACE_SOLID=877,
	XCHG_TYPE_CSG_SOLID=878,
	XCHG_TYPE_BOOLEAN_RESULT=879,
	XCHG_TYPE_SWEPT_AREA_SOLID=880,
	XCHG_TYPE_SOLID_OF_LINEAR_EXTRUSION=881,
	XCHG_TYPE_SOLID_OF_REVOLUTION=882,
	XCHG_TYPE_BOX_DOMAIN=883,
	XCHG_TYPE_BOXED_HALF_SPACE=884,
	XCHG_TYPE_BOOLEAN_OPERAND_ENTITY=885,
	XCHG_TYPE_CSG_SELECT_ENTITY=886,
	XCHG_TYPE_CSG_PRIMITIVE=887,
	XCHG_TYPE_ASSOCIATIVE_ANGULAR_DIMENSION=888,
	XCHG_TYPE_ASSOCIATIVE_CURVE_DIMENSION=889,
	XCHG_TYPE_ASSOCIATIVE_DIAMETER_DIMENSION=890,
	XCHG_TYPE_ASSOCIATIVE_LINEAR_DIMENSION=891,
	XCHG_TYPE_ASSOCIATIVE_RADIUS_DIMENSION=892,
	XCHG_TYPE_ASSOCIATIVE_ORDINATE_DIMENSION=893,
	XCHG_TYPE_FDT=900,
	XCHG_TYPE_TEXT=901,
	XCHG_TYPE_ANNOTATION_ROUGHNESS=902,
	XCHG_TYPE_ANNOTATION = 903,
	XCHG_TYPE_DATUM_TARGET = 904,
	XCHG_TYPE_TABLE_ANNOTATION = 905,
	XCHG_TYPE_GEOM_TOL = 906,
	XCHG_TYPE_DIMENSION = 907,
	XCHG_TYPE_CELL = 908,
	//XCHG_TYPE_SYMBOL = 908,
	XCHG_TYPE_ROUGHNESS = 909,
	XCHG_TYPE_VIEW = 910,
	XCHG_TYPE_DRAWING = 911,
	XCHG_TYPE_WELDING = 912,
	XCHG_TYPE_FDT_ANNOTATION_SET = 913,
	XCHG_TYPE_FDT_VIEW = 914,
    XCHG_TYPE_FDT_CAPTURE = 915,
	XCHG_TYPE_COMPOSITE_ENTITY = 916,
    XCHG_TYPE_GRID,
	XCHG_TYPE_2D_PICTURE,
	XCHG_TYPE_VIEW_DISPLAY,
    XCHG_TYPE_GLOBAL_DATA_SET = 950,
    XCHG_TYPE_SELECTION_DATA_SET,
	XCHG_TYPE_PUBLICATION_DATA_SET,
    XCHG_TYPE_FDT_DATA_SET,
    XCHG_TYPE_FDT_SET,
    XCHG_TYPE_FDT_SET_VIEW,
    XCHG_TYPE_FDT_SET_CAPTURE,
    XCHG_TYPE_FDT_SET_FDT_INFOS,
	XCHG_TYPE_FDT_LINK =998,
	XCHG_TYPE_SOLID_ARRAY=999,
	XCHG_TYPE_OBJECT = 1000,
	XCHG_TYPE_VAL = 1001,
	XCHG_TYPE_ENTITY = 1002,
	XCHG_TYPE_INFO = 1003,
	XCHG_TYPE_MATRIX = 1004,
	XCHG_TYPE_TRANSFO = 1005,
	XCHG_TYPE_GROUP = 1006,
	XCHG_TYPE_2D_ENTITY = 1007,
	XCHG_TYPE_LEADER = 1008,
	XCHG_TYPE_REFERENCE = 1009,
	XCHG_TYPE_REFERENCE_FRAME = 1010,
	XCHG_TYPE_TOL_SPEC = 1011,
	XCHG_TYPE_READ_SHELL=1012,
	XCHG_TYPE_MESH=1013,
	XCHG_TYPE_CAMERA=1014,
	XCHG_TYPE_MESH_CURVE=1015,
	XCHG_TYPE_MESH_STRING=1016,
	XCHG_TYPE_CONNECTOR,
	XCHG_TYPE_CONNECTOR_PART,
	XCHG_TYPE_NODE_CONNECTOR,
	XCHG_TYPE_NODE_CONNECTOR_ENTITY,
	XCHG_TYPE_MODEL_DISPLAY,
	XCHG_TYPE_SECTION,
	XCHG_TYPE_SPECIFICATION_INDICATOR,
	XCHG_TYPE_POINT = 2000,
	XCHG_TYPE_TABLE = 4000,
	XCHG_TYPE_BODY,
	XCHG_TYPE_LUMP,
	XCHG_TYPE_COEDGE,
	XCHG_TYPE_NURBS_CURVE,
	XCHG_TYPE_NURBS_SURFACE,
	XCHG_TYPE_REVOLUTION_SURFACE,
	XCHG_TYPE_STANDARD_REVOLUTION_SURFACE,
	XCHG_TYPE_LINEAR_EXTRUSION_SURFACE,
	XCHG_TYPE_TRANSFORMED_SURFACE,
	XCHG_TYPE_TOL_SPEC_CONT,
	XCHG_TYPE_CABLING,

	XCHG_TYPE_LAYER_INFOS_SET,
	XCHG_TYPE_LAYER_FILTER_INFOS,
	XCHG_TYPE_PREVIEW,
	XCHG_TYPE_GRAPHICAL_DATA,
	XCHG_TYPE_COLOR_INFOS_SET,
		
	XCHG_TYPE_DOCUMENT,
	XCHG_TYPE_DOC_ELEMENT,
	XCHG_TYPE_NODE,
	XCHG_TYPE_COMPONENT,
	XCHG_TYPE_INSTANCE,
	XCHG_TYPE_CATALOG,
	XCHG_TYPE_PROTOTYPE,
	XCHG_TYPE_METADATA,
	XCHG_TYPE_METADATA_GROUP,
	XCHG_TYPE_METADATAWITHUNIT,
	XCHG_TYPE_PROPERTY,
	XCHG_TYPE_ENTITY_LINK,
	XCHG_TYPE_OVERRIDE,
	XCHG_TYPE_OVERRIDE_SET,

	XCHG_TYPE_MATERIAL,
	XCHG_TYPE_MATERIAL_INFOS,
	XCHG_TYPE_MATERIAL_LIBRARY,
	XCHG_TYPE_ASM_CONNECTOR,
	XCHG_TYPE_ASM_SURCHARGE,
	XCHG_TYPE_V6_V5_CONNECTOR,
	XCHG_TYPE_ASM,
	XCHG_TYPE_ASM_TREE,
	XCHG_TYPE_ASM_GRAPHIQUE_ATTR,
	XCHG_TYPE_ASM_PRODUCT_GEOM,
	XCHG_TYPE_ASM_MANAGEREPRESENTATION,
	XCHG_TYPE_MEASURE,
    XCHG_TYPE_MEASURE_PROPERTIES,
	XCHG_TYPE_MESH_FACE,
	XCHG_TYPE_PATCH_SURFACE,

	XCHG_TYPE_PARAMETER_VALUE=10000,
	XCHG_TYPE_NO_SUBTYPE = 10028, 

	XCHG_TYPE_FEATURE,
	XCHG_TYPE_KINEMATIC,
	XCHG_TYPE_KIN_NAMED_VALUE,
	XCHG_TYPE_KIN_CONSTRAINT,
	XCHG_TYPE_KIN_MECHANISM,
	XCHG_TYPE_KIN_PARAMETER,
	XCHG_TYPE_KIN_COMMAND,
	XCHG_TYPE_KIN_JOINT,
	XCHG_TYPE_KIN_LAW,
	XCHG_TYPE_KIN_SPEEDACCELERATION,
	XCHG_TYPE_KIN_FIXPART,
	XCHG_TYPE_KIN_CURVE,
	XCHG_TYPE_KIN_PRODUCT,
	XCHG_TYPE_KIN_FORMULA,

	XCHG_TYPE_HATCHING,
    XCHG_TYPE_REGION, //

	XCHG_TYPE_ASMSEARCHPATH,

	XCHG_TYPE_CONNECTR_ECP,   // Special Catia V4 Connector ECP type
	XCHG_TYPE_SELECTION_SET,  // Selection Set Entity : enables selection multiple entities in a CAD Model
	XCHG_TYPE_PUBLICATION,  // Publication Entity : enables publishing entities in a CAD Model in order to make available for different users

	XCHG_TYPE_BLEND_BOUND,
	XCHG_TYPE_TEXTURE,
	XCHG_TYPE_LIGHT,
	XCHG_TYPE_RENDER,
    XCHG_TYPE_GEOMETRY,
	XCHG_TYPE_CENTER_POINT,
    XCHG_TYPE_SKETCH,

	XCHG_TYPE_SPCURVE,
	XCHG_TYPE_DNBIGPTAG_AXIS_SYSTEM,
	// NC related types
	XCHG_TYPE_NC_PROJECT,
	XCHG_TYPE_NC_WORKPLAN,
	XCHG_TYPE_NC_WORKPIECE,
	XCHG_TYPE_NC_EXECUTABLE,
	XCHG_TYPE_NC_PROGRAM_STRUCTURE,
	XCHG_TYPE_NC_FUNCTION,
	XCHG_TYPE_NC_WORKINGSTEP,
	//XCHG_TYPE_NC_WORKPIECE,
	XCHG_TYPE_NC_MANUFACTURING_FEATURE,
	XCHG_TYPE_NC_MACHINING_FEATURE,
	XCHG_TYPE_NC_OPERATION,
	XCHG_TYPE_NC_TECHNOLOGY,
	XCHG_TYPE_NC_STRATEGY,
	XCHG_TYPE_NC_TOOL,
	XCHG_TYPE_NC_TOOLPATH,

	XCHG_TYPE_PICTURE,
	XCHG_TYPE_INTLOG,
	XCHG_TYPE_LOG,

	XCHG_TYPE_PARASOLIDCURVE,
	XCHG_TYPE_PARASOLIDSURFACE,

	XCHG_TYPE_REFERENCE_AXIS_SYSTEM,
	XCHG_TYPE_REFERENCE_AXIS,
	XCHG_TYPE_REFERENCE_PLANE,
	XCHG_TYPE_REFERENCE_PLANE_TRIANGLE,
	XCHG_TYPE_REFERENCE_POINT,

	XCHG_TYPE_BUILDING_MATERIAL,
	XCHG_TYPE_CONSTRAINT,
	XCHG_TYPE_CONSTRAINT_REFERENCE,

	XCHG_TYPE_MESH_SURFACE,
	XCHG_TYPE_CLOUD_BODY,
	XCHG_TYPE_MESH_GRAPHIC,

	XCHG_TYPE_LINE_TYPE_DEFINITION,

	XCHG_TYPE_OLE_OBJECT,
	XCHG_TYPE_STOREDINFO,
	XCHG_TYPE_STREAM,
	XCHG_TYPE_ADVANCED_FEATURE,
	XCHG_TYPE_PROPERTIES,
	XCHG_TYPE_MESH_POLYLINE,

	XCHG_TYPE_MAX_ENTITY   // Keep at the end
} ;

#define XCHG_MAX(a,b) ((a)>(b) ? (a):(b))
#define XCHG_MIN(a,b) ((a)<(b) ? (a):(b))

#define XCHG_BOUND(x, Min, Max) (XCHG_MAX(XCHG_MIN((x), Max), Min))


#ifdef WIN32

typedef signed __int8 Int8;
typedef unsigned __int8 UInt8;
typedef __int32 Int32;
typedef __int64	Int64;
typedef unsigned __int32 UInt32;
typedef unsigned __int64 UInt64;
typedef __int16 Short16;
typedef unsigned __int16 UShort16;
typedef unsigned __int32 ID;


#else //#ifdef WIN32

typedef int8_t Int8;
typedef uint8_t UInt8;
typedef int32_t Int32;
typedef uint32_t UInt32;
typedef int16_t Short16;
typedef uint16_t UShort16;
typedef int64_t Int64;
typedef uint64_t UInt64;
typedef uint32_t ID;

#endif //#ifdef WIN32

typedef ID Xchg_ID;
typedef Xchg_ID Xchg_ComponentID;
typedef Xchg_ID Xchg_NodeID;

typedef char Char8;
typedef unsigned char UChar8;
typedef double Double64;
typedef float Float32;

#define XCHG_TRUE 1
#define XCHG_FALSE 0
using Xchg_bool = bool;
using Xchg_Int32=Int32;
using Xchg_UInt32=UInt32;
using Xchg_Int64=Int64;
using Xchg_UInt64=UInt64;
using Xchg_Short16=Short16;
using Xchg_UShort16=UShort16;
using Xchg_Char8=Char8;
using Xchg_UChar8=UChar8;
using Xchg_Double64=Double64;
using Xchg_Float32=Float32;




/*
#define STRING2(x) #x
#define STRING(x) STRING2(x)
#pragma message ("MSC_VER ="  STRING(_MSC_VER) )
*/
#if !defined(__APPLE__) && (_MSC_VER > 1800)
typedef std::ptrdiff_t Ptrdiff_t;
#else
typedef ptrdiff_t Ptrdiff_t;
#endif
typedef wchar_t WChar_t;
typedef size_t Size_t;
using Xchg_Size_t = Size_t;
using Xchg_WChar_t = WChar_t;


#if( defined(WIN32)  /*|| COMPILATEUR == 6*/ ) /* if you uncomment COMPILATEUR == 6 dxfread will build but v5read will not*/
typedef fpos_t  Fpos_t;
typedef fpos_t  fpos_xchg;
#elif ( COMPILATEUR == 5 || COMPILATEUR == 2 || COMPILATEUR == 4 )
typedef long long Fpos_t;
typedef long long fpos_xchg;
#else
typedef unsigned long Fpos_t;
typedef unsigned long fpos_xchg;
#endif
typedef char Bool;
#define XCHG_TRUE 1
#define XCHG_FALSE 0

#define XCHG_UNUSED(a) ((void)(a))


#ifdef _DEBUG_XCHG
#pragma message( " Warning : _DEBUG_XCHG is defined  for internal debug!!!" )
#define XCHG_ASSERT(expr) assert(expr)
#define XCHG_ASSERT_MSG(expr, msg) assert((expr)&&(msg))
#else
#define XCHG_ASSERT(expr) ((void)0)
#define XCHG_ASSERT_MSG(expr, msg) ((void)0)
#endif

#if !defined(XCHG_NO_CXX11_NOEXCEPT)
# define XCHG_NOEXCEPT noexcept
# define XCHG_NOEXCEPT noexcept
# define XCHG_NOEXCEPT_IF(Predicate) noexcept((Predicate))
# define XCHG_NOEXCEPT_EXPR(Expression) noexcept((Expression))
#else
# define XCHG_NOEXCEPT
# define XCHG_NOEXCEPT_IF(Predicate)
# define XCHG_NOEXCEPT_EXPR(Expression) false
#endif


typedef std::nullptr_t nullptr_type;  

#include "base/xchg_error.hpp"


#endif
